name: Build and Deploy Docs
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.6.0]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install 💾
        run: npm install

      - name: Build HTML Docs 🔨
        run: npm run doc:html

      - name: Build JSON Docs 🔨
        run: npm run doc:json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist/docs
