name: Tests CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Contracts
        uses: actions/checkout@main
        with:
          name: LibertyDSNP/contracts
          ref: refs/heads/main
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Compile
        run: npm run compile
      - name: Setup node
        run: npx hardhat compile
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.5'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Docs
        run: npm run doc

      - name: Build & Publish Dry Run
        run: npm publish --dry-run

#      - name: Test
#        run: npm run test

#      - name: Report Test
#        uses: IgnusG/jest-report-action@v2.3.3
#        if: always()
#        with:
#          access-token: ${{ secrets.GITHUB_TOKEN }}
